#!/usr/bin/env bash
# script that transfer a file from a client to remote server
# $1 => path to the file to be transferred
# $2 => IP of the server we want to transfer the file to
# $3 => username scp connects with
# $4 => path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
