#!/usr/bin/env bash
# configure a web server to display "hello world" and listen to port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" > 404.html
sudo mv -f 404.html /var/www/html

echo "server {
        listen 80 default_server;

        root /var/www/html;
        index index.html;

        location /redirect_me {
                return 301 https://www.digitalocean.com/community/;
        }

        error_page 404 /404.html;
        location = /404.html {
                root /var/www/html;
                internal;
        }
}" > default_file
sudo mv -f default_file /etc/nginx/sites-enabled/default
sudo service nginx restart
