#!/usr/bin/env bash
# script that debug and configures nginx server to listen to port 80
sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
pkill -9 nginx
service nginx restart
