#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# using the while loop + IFS

while IFS=":" read -r username passwd uid gid info home shell; do
	echo "The user $username is part of the $gid gang, lives in $home" \
	"and rides $shell. $uid's place is protected by the passcode" \
	"$passwd, more info about the user here: $info"
done < "/etc/passwd"
