#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.new

#remove and add host name address
sed -i 's/127.0.0.1\s*localhost//g' /etc/hosts.new
echo -e "127.0.0.2 \t localhost" >> /etc/hosts.new

#adding facebook address
echo -e "8.8.8.8 \t facebook.com" >> /etc/hosts.new

cp -f /etc/hosts.new /etc/hosts
